### ISSUE TITLE
Tree Editor template fails on Theia next

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/generator-theia-extension#124]
There are build errors when generating the tree-editor template on Theia next

**Comment by JonasHelming** [comment]
@lucas-koehler : Is it possible to fix this?

**Comment by lucas-koehler** [comment]
I will investigate later this week

**Comment by lucas-koehler** [comment]
I investigated this and as far as I can tell the root cause of this is incorrect versioning of Theia's published `next` version.
Looking at https://www.npmjs.com/package/@theia/core/, the most recent `next` version is `1.18.0-next.177`. However the `latest` version is `1.20.0`.
With this, the `next` version is not newer than the `latest` version from the point of view of semantic versioning. This leads to the problem that the tree editor's dependency `^1.18.0` is resolved to `1.20.0` while `next` is resolved to `1.18.0-next.177`.
I would expect that the `next` versions released after `1.20.0` are of format `1.21.0-next.1`. This was always the case until `1.19.0`. For some reason, the version number of the next version did not increase with the `1.19.0` (and the `1.20.0`) release.

With different versions being resolved, the types are not compatible and, thus, the extension cannot be built.

**Comment by JonasHelming** [comment]
@vince-fugnitto : Can you comment on this?

**Comment by vince-fugnitto** [comment]
After a little bit of effort `next` releases should now be fixed, you can now confirm if that was the cause of the issues related to the tree-editor.

**Comment by lucas-koehler** [comment]
Thank you very much for the quick fix, @vince-fugnitto . Unfortunately, this did not fix it because apparently versions like `^1.18.0` are not resolved to `next`. But I guess it was good to fix that anyway :)

Another idea I tried was to set `resolutions` in the root `package.json`. However, resolutions cannot be resolved to dist-tags (like `next`). See this issue on the yarn repository https://github.com/yarnpkg/yarn/issues/6666 . If resolving to the most recent next version by using it's version directly, everything builds fine. Consequently, it definitely is a resolution issue and not related to changes in Theia itself.

I will investigate a solution in the tree editor package itself (e.g. peer depenencies for Theia).

**Comment by lucas-koehler** [comment]
@JonasHelming With the latest version of the tree editor, the generation should now work with Theia next.

**Comment by JonasHelming** [comment]
works for me
